/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans:     ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Inter'],
        body:     ['Inter'],
        label:    ['Inter'],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:   "0.5rem",
        xl:   "0.75rem",
        full: "9999px",
      },
      colors: {
        /* ── Brand ramp kept for backwards-compat with existing pages ── */
        brand: {
          50:  '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },

        /* ── Material-3 inspired tokens used by the /chat page ── */
        "inverse-surface":            "#2d3133",
        "inverse-primary":            "#b4c5ff",
        "on-primary-container":       "#eeefff",
        "tertiary":                   "#0d9488",
        "secondary-fixed-dim":        "#b9c7df",
        "on-surface-variant":         "#434655",
        "surface-container-low":      "#f2f4f6",
        "on-tertiary-container":      "#f0fdfa",
        "on-secondary-container":     "#57657a",
        "outline":                    "#737686",
        "surface-container-high":     "#e6e8ea",
        "surface-dim":                "#d8dadc",
        "surface-container-lowest":   "#ffffff",
        "background":                 "#f7f9fb",
        "surface-bright":             "#f7f9fb",
        "on-primary-fixed-variant":   "#003ea8",
        "error":                      "#ba1a1a",
        "tertiary-fixed-dim":         "#99f6e4",
        "secondary":                  "#515f74",
        "primary-fixed":              "#dbe1ff",
        "surface-container":          "#eceef0",
        "primary":                    "#1e3a8a",
        "primary-container":          "#0f172a",
        "primary-fixed-dim":          "#b4c5ff",
        "inverse-on-surface":         "#eff1f3",
        "on-tertiary":                "#ffffff",
        "on-secondary":               "#ffffff",
        "on-error-container":         "#93000a",
        "secondary-container":        "#d5e3fc",
        "on-secondary-fixed-variant": "#3a485b",
        "on-secondary-fixed":         "#0d1c2e",
        "secondary-fixed":            "#d5e3fc",
        "surface-tint":               "#1e3a8a",
        "on-primary-fixed":           "#00174b",
        "on-background":              "#191c1e",
        "tertiary-fixed":             "#ccfbf1",
        "on-primary":                 "#ffffff",
        "surface":                    "#f7f9fb",
        "tertiary-container":         "#0d9488",
        "on-tertiary-fixed":          "#042f2e",
        "on-tertiary-fixed-variant":  "#0f766e",
        "outline-variant":            "#c3c6d7",
        "surface-container-highest":  "#e0e3e5",
        "surface-variant":            "#e0e3e5",
        "on-surface":                 "#191c1e",
        "error-container":            "#ffdad6",
        "on-error":                   "#ffffff",
        "brand-teal":                 "#2dd4bf",
      },
    },
  },
  plugins: [],
}
